Enable usage of external btrfs as /data
trustm3/meta-trustx pull request #120
Opened 2021-02-05 14:08 UTC by ceppleaisec

Allow usage of externally provided 9p btrfs to be mounted
as overlay over /mnt/userdata to /data. This enables the user
i.a. to work with larger guestsOSes in a virtualized environment.

2021-02-16 20:11 UTC, quitschbo requested changes

2021-02-16 20:11 UTC, quitschbo commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +mount -t overlay overlay -o lowerdir=/mnt/userdata,upperdir=/mnt/extdata/data,workdir=/mnt/extdata/workdir /data
do not try to mount the overlay if mount of /mnt/extdata fails
merge this into then case above

2021-02-16 20:11 UTC, quitschbo commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +   echo "No extdata fs supplied"
directly mount userdata here

2021-02-16 20:11 UTC, quitschbo commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +    mount -o bind,nosuid,nodev,noexec /mnt/userdata /data
merge as state in else case above

2021-02-22 08:51 UTC, ceppleaisec commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +   echo "No extdata fs supplied"
done

2021-02-22 08:51 UTC, ceppleaisec commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +mount -t overlay overlay -o lowerdir=/mnt/userdata,upperdir=/mnt/extdata/data,workdir=/mnt/extdata/workdir /data
done

2021-02-22 08:51 UTC, ceppleaisec commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +   echo "No extdata fs supplied"
done

2021-02-22 08:51 UTC, ceppleaisec commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +    mount -o bind,nosuid,nodev,noexec /mnt/userdata /data
done

2021-02-23 10:35 UTC, quitschbo requested changes

2021-02-23 10:35 UTC, quitschbo commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +	mount -t overlay overlay -o lowerdir=/mnt/userdata,upperdir=/mnt/extdata/data,workdir=/mnt/extdata/workdir /data
fix indentation

2021-02-23 12:45 UTC, ceppleaisec commented on recipes-initscripts/cml-boot/files/cml-boot-script.stub
> +	mount -t overlay overlay -o lowerdir=/mnt/userdata,upperdir=/mnt/extdata/data,workdir=/mnt/extdata/workdir /data
done

2021-02-23 12:47 UTC, ceppleaisec commented
I have also added the -p switch to the mkdir commands to suppress warnings if the directories have already been created

2021-02-24 10:03 UTC, quitschbo approved these changes

2021-02-24 10:03 UTC, merged